### ISSUE TITLE
Pypi version not aligned with git releases.

### ISSUE THREAD

**Issue by x-warrior** [cameronmaske/celery-once#102]
I just noticed that on PyPi there is a version 3.0 but here there is not.

Is this correct? It felt super weird to have a version 3.0 there and not here. 

https://pypi.python.org/pypi/celery_once/

**Comment by cameronmaske** [comment]
Thanks for the heads up. [3.0.0 tag created](https://github.com/cameronmaske/celery-once/releases/tag/3.0.0)
