### ISSUE TITLE
Issue working with Sentry celery integration

### ISSUE THREAD

**Issue by mumumumu** [cameronmaske/celery-once#105]
I'm trying to use `celery-once` with the Sentry celery integration, but I'm running into an issue with how Sentry patches the task tracer. 

The issue I'm seeing is that the key before and after the task is patched are different. I believe this is because of how `inspect.getcallargs` is working with Sentry's wrapped `run` method. 

Would there be anything wrong with storing the key on the task instance like this:
```py
    def get_key(self, args=None, kwargs=None):
        """
        Generate the key from the name of the task (e.g. 'tasks.example') and
        args/kwargs.
        """
        if not hasattr(self, '_key'):
            restrict_to = self.once.get('keys', None)
            args = args or {}
            kwargs = kwargs or {}
            call_args = getcallargs(
                    getattr(self, '_orig_run', self.run), *args, **kwargs)
            # Remove the task instance from the kwargs. This only happens when the
            # task has the 'bind' attribute set to True. We remove it, as the task
            # has a memory pointer in its repr, that will change between the task
            # caller and the celery worker
            if isinstance(call_args.get('self'), Task):
                del call_args['self']
            self._key = queue_once_key(self.name, call_args, restrict_to)
        return self._key
```

**Comment by mumumumu** [comment]
Actually, it looks like this can be fixed on Sentry's side.

**Comment by cameronmaske** [comment]
Hi @mumumumu thanks for reporting. 
Is this still an issue, or is it solved by https://github.com/getsentry/sentry-python/issues/421?

**Comment by mackthehack** [comment]
I'm currently experiencing this issue as well - even after the monkey patch change in the Sentry SDK.
I'm using celery_once 3.0.0 and sentry_sdk 0.10.2 (which includes the monkey patch changes to the method from the above referenced fix). Turning off the celery integration for sentry in settings removes the error. 

` [2019-08-12 10:39:02,867: WARNING/ForkPoolWorker-4]  RuntimeWarning: Exception raised outside body: KeyError('company_id',):
Traceback (most recent call last):
  File "/envs/lib/python3.6/site-packages/celery/app/trace.py", line 472, in trace_task
    state, retval, uuid, args, kwargs, None,
  File "/envs/lib/python3.6/site-packages/celery_once/tasks.py", line 129, in after_return
    key = self.get_key(args, kwargs)
  File "/envs/lib/python3.6/site-packages/celery_once/tasks.py", line 118, in get_key
    key = queue_once_key(self.name, call_args, restrict_to)
  File "/envs/lib/python3.6/site-packages/celery_once/helpers.py", line 72, in queue_once_key
    restrict_kwargs = {key: kwargs[key] for key in restrict_to}
  File "/envs/lib/python3.6/site-packages/celery_once/helpers.py", line 72, in <dictcomp>
    restrict_kwargs = {key: kwargs[key] for key in restrict_to}
KeyError: 'company_id'`

**Comment by cameronmaske** [comment]
@mackthehack Are you on Python 2?
If so the latest version of celery once (3.0.1) and this branch for the sentry sdk https://github.com/getsentry/sentry-python/pull/475 should fix your issue.

**Comment by mackthehack** [comment]
I'm using python 3.6.

**Comment by cameronmaske** [comment]
Can you try 3.0.1 and see if that fixes the error? It changes how keys are generated.

**Comment by cameronmaske** [comment]
3.0.1 should resolve this issue. I'll re-open if anyone else experiences this.
