### ISSUE TITLE
Task with base OnceQueue causes my celery task invisible.

### ISSUE THREAD

**Issue by fatihsucu** [cameronmaske/celery-once#23]
When i use rabbitmq as my celery broker it works fine. But if i prefer to use redis as celery broker and celery-once broker at same time my `OnceQueue` task becomes invisible. Worker doesn't receive that task.

By the way, if i remove `OnceQueue` it works fine too.

**Comment by cameronmaske** [comment]
Hey @fatihsucu, sorry this issue slipped by my notice. 
I haven't experienced this using celery + redis + celery_once. So I'm not really sure how to debug this.
Example code/repo that demonstrates how to replicate would be incredibly helpful to debugging it further.
