### ISSUE TITLE
Support redlock

### ISSUE THREAD

**Issue by dkiser** [cameronmaske/celery-once#35]
Given That I am a celery-once consumer, I Should Be Able To Configure the use of [redlock](https://github.com/glasslion/redlock) as provider So That I Can take advantage of the [distlock](http://redis.io/topics/distlock) algorithm to solve redis replication race conditions.

**Comment by dkiser** [comment]
We can probably add a new provider once https://github.com/TrackMaven/celery-once/pull/16 is merged in for a `RedLock` class or something?

**Comment by cameronmaske** [comment]
Multiple backend support is merged in for 1.0.0. If this is still desired to feel free to re-open the issue (or a PR is welcome). A guide to writing locking backends is here https://github.com/cameronmaske/celery-once/blob/master/BACKEND_GUIDE.rst
