### ISSUE TITLE
Long running tasks do not seem to hold the lock 

### ISSUE THREAD

**Issue by VidJa** [cameronmaske/celery-once#36]
I have some very long running processes (48-60h) but I've noticed the running tasks are released before the task finishes an thus other workers start processing the same task. 
If I simulate the long task by a simple sleep command of a few minutes, all task locks are preserved as expected. Am I missing a setting?
Below are my settings for Celery 3.1.20

`# -_\- coding: utf-8 -_-
BROKER_URL = 'redis://localhost:6379/8'

BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 262800}  # 73 hours.
# Celery result backend

CELERY_RESULT_BACKEND = 'redis://localhost:6379/8'
CELERY_RESULT_PERSISTENT = True

CELERY_ACKS_LATE = True
CELERYD_CONCURRENCY = 1
CELERYD_PREFETCH_MULTIPLIER = 1

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT=['json']
CELERY_TIMEZONE = 'Europe/Amsterdam'
CELERY_ENABLE_UTC = True
# List of modules to import when celery starts.

CELERY_IMPORTS = ('worker.tasks', )
# CeleryOnce for task locking

ONCE_REDIS_URL = 'redis://localhost:6379/8'
ONCE_DEFAULT_TIMEOUT = 259200 # 72 hours
`

**Comment by cameronmaske** [comment]
@VidJa Super delayed reply, apologies for that. 
One thing that maybe is having an effect is timeout start from when the task is called.
Any chance they could be in the queue for several hours (10+) that it total time goes past 72 hours? If this is still an issue, feel free to re-open.
