### ISSUE TITLE
cannot be used as base class?

### ISSUE THREAD

**Issue by Zuckonit** [cameronmaske/celery-once#42]
in celery 4.0, we can use class to create a task as:

```
from celery.task import Task

class DemoTask(Task):
    
    def run(self, *args, **kwargs):
        #do something
```

but if using celery-once, how to do that? I am trying to: 

```
from celery_once import QueueOnce

class DemoTask2(QueueOnce):
    
    def run(self, *args, **kwargs):
        #do something
```
but ```DemoTask2``` task do not be loaded

**Comment by zachmccormick** [comment]
Try using:
```class SomeTask(Task, QueueOnce):```

I believe this is working for me.

**Comment by cameronmaske** [comment]
Thanks for the suggestion zachmccormick. Hope it resolved your issue Zuckonit.
