### ISSUE TITLE
Support other backends than Redis

### ISSUE THREAD

**Issue by jezdez** [cameronmaske/celery-once#5]
Memcache comes to mind for distributed locks and it'd be nice to use that instead of Redis if it's more likely to be available than Redis

**Comment by cameronmaske** [comment]
This would be a really nice extension. Currently the code is very coupled to redis. 
Creating a plugin backend's structure would be the way to go ([docker-swarm](https://github.com/docker/swarm/tree/master/discovery#contributing) is an good example of extendable backends). 

Seems the backend would need two main functions...
* [`raise_or_lock`](https://github.com/TrackMaven/celery-once/blob/dbce7508536eb8a2d3184dd2dded42a86357882c/celery_once/tasks.py#L98)
* [`clear_lock`](https://github.com/TrackMaven/celery-once/blob/dbce7508536eb8a2d3184dd2dded42a86357882c/celery_once/tasks.py#L116)

**Comment by brouberol** [comment]
I'm willing to give this a try, but I have no knowledge of memcache's API. @jezdez, if I provide a way to support it by implementing a MemcacheBackend (or similar) class implementing the API described earlier, could you take car of the memcache specifics?

**Comment by jezdez** [comment]
@brouberol Sure, I can take a stab at a Memcache backend next week!

**Comment by brouberol** [comment]
@jezdez Awesome! My proposal for multiple backend support is currenly waiting for a green light from @cameronmaske. I guess you can build on the existing code, and I'll take care of any change if any API change is required.

**Comment by jezdez** [comment]
@brouberol Sounds good to me, depending if @cameronmaske likes the API I'll either send a PR to you or this repo.. :)

**Comment by cameronmaske** [comment]
@jezdez Yup, the API looks great! I'm gonna attempt to get @brouberol PR merged in to a `1.0rc` branch by the end of this weekend. But, feel free to pass your memcache support off the API paradigm!

**Comment by cameronmaske** [comment]
@brouberol Modification made! See #21. The docs just need updating, which I'll hopefully be able to get to later this week. 
@jezdez If you have a PR, could you base if off and point it towards the `1.0-rc` branch? If it's helpful here is a draft on the [backend contributing guide](https://gist.github.com/cameronmaske/742cd7daf74657b37fdc)

**Comment by cameronmaske** [comment]
Long overdue, but this is now in master. 
See: https://github.com/cameronmaske/celery-once/blob/master/BACKEND_GUIDE.rst for a guide to adding custom backends.

**Comment by brouberol** [comment]
Great! Cheers :) 

--
B


On Tue, Jun 6, 2017, at 05:44 PM, Cameron Maske wrote:
> Long overdue, but this is now in master.
>  See:
>  https://github.com/cameronmaske/celery-once/blob/master/BACKEND_GUIDE.rst
>  for a guide to adding custom backends.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/cameronmaske/celery-once/issues/5#issuecomment-306528391
