### ISSUE TITLE
Is there a way to set graceful to True globally?

### ISSUE THREAD

**Issue by hugobessa** [cameronmaske/celery-once#61]
I'd like to fail gracefully for every task except some few, so setting this to True globally would be really nice. Is it possible?

**Comment by cameronmaske** [comment]
@hugobessa Super delayed getting back to you.
Currently there is not, but I'd be happy to take a PR that adds it to the settings, e.g.

```
celery.conf.ONCE = {
  'backend': 'celery_once.backends.Redis',
  'graceful': True,
   ....
}
```
It would work very similar to the `default_timeout` logic.
https://github.com/cameronmaske/celery-once/blob/master/celery_once/tasks.py#L88

**Comment by cameronmaske** [comment]
I'm gonna close this out for now, if anyone else is interested in taking this forward, happy to re-open/discuss!
