### ISSUE TITLE
Is there a SSL support for Redis?

### ISSUE THREAD

**Issue by michelpf** [cameronmaske/celery-once#62]
I'm trying to make it work with SSL connection using Redis on Azure, but with no sucess.
Could you confirm if it's possible?

On Celery, it is, https://github.com/celery/celery/pull/3831.

**Comment by michelpf** [comment]
There is!
 'redis://host:port/0?password=password=&ssl=True',

**Comment by gustavoalmeida** [comment]
Hello all

What about urls with **rediss://**? We are not allowing this protocol here?
https://github.com/cameronmaske/celery-once/blob/master/celery_once/backends/redis.py#L29
