### ISSUE TITLE
Use SETNX when setting the lock

### ISSUE THREAD

**Issue by frewsxcv** [cameronmaske/celery-once#7]
http://redis.io/commands/setnx

This would prevent a race condition in which a lock is set multiple times. The result would need to be checked to make sure the lock was successfully set.

**Comment by cameronmaske** [comment]
Read more about this! This [article](https://engineering.gosquared.com/distributed-locks-using-redis) does a good job diving into more details of why it would be useful. 
This is worth doing, thanks for the heads up!

**Comment by ntcong** [comment]
If anyone has interest in this, I have 1 PR but in Tripadvisor's fork (because they are much newer)
https://github.com/tripadvisor/celery-once/pull/4

**Comment by blueyed** [comment]
@ntcong 
Thanks.

@cameronmaske 
Is the project still maintained?
https://github.com/TrackMaven/celery-once/pull/34 would be nice to have merged, too.

**Comment by jheld** [comment]
@cameronmaske are you considering using Redlock, or something else? Seems SETNX is a decent solution, but even they talk about Redlock.

**Comment by cameronmaske** [comment]
Closing out a 3 year old ticket!  Better late then never I guess.
This is live on `2.0.0` enjoy.
