### ISSUE TITLE
Getting celery beat error 'SchedulingError: Couldn't apply scheduled task'

### ISSUE THREAD

**Issue by kowsari** [cameronmaske/celery-once#72]
Hi,
Thank you for writing a useful project for celery.

I am attempting to use this with scheduled tasks that run every minute that are configured in settings.py using celery beat config like below:
```
CELERYBEAT_SCHEDULE = {
    'check_products': {
      'task': 'com.ixlayer.tasks.check_products', 'schedule': timedelta(minutes=1),
    },
}


```

However sometimes I get an exception in the process that runs celery beat.
```
Traceback (most recent call last):
  File "/Users/kowsari/workspace/ixlayer-be/venv/lib/python2.7/site-packages/celery/beat.py", line 222, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File "/Users/kowsari/workspace/ixlayer-be/venv/lib/python2.7/site-packages/celery/beat.py", line 328, in apply_async
    entry, exc=exc)), sys.exc_info()[2])
  File "/Users/kowsari/workspace/ixlayer-be/venv/lib/python2.7/site-packages/celery/beat.py", line 320, in apply_async
    **entry.options)
  File "/Users/kowsari/workspace/ixlayer-be/venv/lib/python2.7/site-packages/celery_once/tasks.py", line 99, in apply_async
    raise e
SchedulingError: Couldn't apply scheduled task check_products:
```
I am using this configuration.
```
app.conf.ONCE = {
  'backend': 'celery_once.backends.Redis',
  'settings': {
    'url': settings.BROKER_URL,
    'default_timeout': 60 * 60
  }
}

```
Is this celerybeat getting the AlreadyQueued exception? Or is this something else?
Help is much appreciated.

Thanks

**Comment by cameronmaske** [comment]
Hey @kowsari 
This is probably something else! We currently don't have any tests for scheduled tasks, so most likely this is a bug with celery_once. 

To help debug this further, what version of celery are you using?

**Comment by kowsari** [comment]
Thanks @cameronmaske,
I am using Celery 4.1.0.

So I added a base=QueueOnce to my tasks which makes the problem go away, which makes sense to me. This could be the way to avoid the SechedulingErors.

But the problem that I have now sometimes (which I am not sure it is related to this) is that sometimes when my worker and beat starts...beat send the tasks, but they never get picked up by the workers. If I change the code and remove the QueueOnce then the workers pickup the tasks.

Thanks for your help.!

**Comment by xuhcc** [comment]
I had a very similar problem with periodic task, and solution was to add `graceful=True` to its options:

```python
@shared_task(base=QueueOnce, once={'graceful': True})
def my_task():
    ...
```

In my case `AlreadyQueued` exception was invisible due to logging config, so everything looked like a worker not picking up tasks.

**Comment by fanchunke1991** [comment]
recently, we met a very similar problem with periodic task. we use `redis backend` and `redis-once`.

In my case, when `celery beat` scheduled a task, it published a message to redis. But in some reasons, redis closed the connection, so it raised an Exception: `SchedulingError: Couldn't apply scheduled task`.

Actually, the message had not been published to redis, but `celery-once` had set a lock for the task, and it isn't released until the default timeout has expired. So `celery beat` would't send another task, and everything just looked like `celery worker` not picking up tasks.

So any solutions for this problem?  Help is much appreciated.

**Comment by dulobanov** [comment]
I have very similar issue. It looks like celery beat can not connect to redis. I'm able to connect to redis from the same container and save data in it.
`
celerybeat_1      | Traceback (most recent call last):
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 665, in send_packed_command
celerybeat_1      |     self._sock.sendall(item)
celerybeat_1      | ConnectionResetError: [Errno 104] Connection reset by peer
celerybeat_1      | 
celerybeat_1      | During handling of the above exception, another exception occurred:
celerybeat_1      | 
celerybeat_1      | Traceback (most recent call last):
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 359, in apply_async
celerybeat_1      |     **entry.options)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
celerybeat_1      |     **options
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 755, in send_task
celerybeat_1      |     self.backend.on_task_call(P, task_id)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 294, in on_task_call
celerybeat_1      |     self.result_consumer.consume_from(task_id)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 136, in consume_from
celerybeat_1      |     self._consume_from(task_id)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 142, in _consume_from
celerybeat_1      |     self._pubsub.subscribe(key)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 3246, in subscribe
celerybeat_1      |     ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 3141, in execute_command
celerybeat_1      |     self._execute(connection, connection.send_command, *args, **kwargs)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 3145, in _execute
celerybeat_1      |     return command(*args, **kwargs)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 686, in send_command
celerybeat_1      |     check_health=kwargs.get('check_health', True))
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 678, in send_packed_command
celerybeat_1      |     (errno, errmsg))
celerybeat_1      | redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
celerybeat_1      | 
celerybeat_1      | During handling of the above exception, another exception occurred:
celerybeat_1      | 
celerybeat_1      | Traceback (most recent call last):
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 242, in apply_entry
celerybeat_1      |     result = self.apply_async(entry, producer=producer, advance=False)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 367, in apply_async
celerybeat_1      |     entry, exc=exc)), sys.exc_info()[2])
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
celerybeat_1      |     raise value.with_traceback(tb)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 359, in apply_async
celerybeat_1      |     **entry.options)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
celerybeat_1      |     **options
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 755, in send_task
celerybeat_1      |     self.backend.on_task_call(P, task_id)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 294, in on_task_call
celerybeat_1      |     self.result_consumer.consume_from(task_id)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 136, in consume_from
celerybeat_1      |     self._consume_from(task_id)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/celery/backends/redis.py", line 142, in _consume_from
celerybeat_1      |     self._pubsub.subscribe(key)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 3246, in subscribe
celerybeat_1      |     ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 3141, in execute_command
celerybeat_1      |     self._execute(connection, connection.send_command, *args, **kwargs)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 3145, in _execute
celerybeat_1      |     return command(*args, **kwargs)
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 686, in send_command
celerybeat_1      |     check_health=kwargs.get('check_health', True))
celerybeat_1      |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 678, in send_packed_command
celerybeat_1      |     (errno, errmsg))
celerybeat_1      | celery.beat.SchedulingError: Couldn't apply scheduled task pressure: Error 104 while writing to socket. Connection reset by peer.
`

**Comment by cameronmaske** [comment]
As a workaround, for now, I'd suggest using a pure celery task to trigger celery once task, i.e. 

```
CELERYBEAT_SCHEDULE = {
    'example': {
      'task': 'tasks.scheduled_task', 'schedule': timedelta(minutes=1),
    },
}

@task()
def scheduled_task():
	scheduled_once_task.delay()

@task(base=QueueOnce)
def scheduled_once_task():
	....
```

I don't have the bandwidth currently to fix this, but a PR (while it may be tricky, please include a test case for a scheduled task to aid the review) is welcome.
