### ISSUE TITLE
celey_once does not work

### ISSUE THREAD

**Issue by EyecatWang** [cameronmaske/celery-once#80]
I set up a task with celecy. Repeated multiple times. so i used celecy-once. but also can't.
![wechatimg9](https://user-images.githubusercontent.com/26106551/49645522-3bf7e280-fa57-11e8-9582-46f50434cdb6.png)

![wechatimg10](https://user-images.githubusercontent.com/26106551/49645579-719ccb80-fa57-11e8-8194-145b7cc53c58.png)

**Comment by cameronmaske** [comment]
@BlingHong
Could you post the full code of the task and how you are running the task?
Also, could you include which version of python + celery you are using?

**Comment by cameronmaske** [comment]
@KyrumX @EyecatWang  Are the tasks you are trying run `periodic` tasks, i.e. scheduled by django celery beat? If so #72 is maybe related?

This one is a bit issue to debug further. Any chance you could provide a minimal example project that reproduces the issue?

**Comment by cameronmaske** [comment]
Closing this out due to inactivity. If this is still an issue (or someone else encounters it) feel free comment and we can re-open.
