### ISSUE TITLE
Test with real Redis on Travis

### ISSUE THREAD

**Issue by frewsxcv** [cameronmaske/celery-once#9]
Travis allows an instance of Redis to be run when testing

http://docs.travis-ci.com/user/database-setup/#Redis

It'd be great if tests ran using that instead of FakeRedis

**Comment by cameronmaske** [comment]
@frewsxcv running against a real redis would be a more complete integration tests. The only issue I see is I like having the ability to run all tests locally, so this would mean supporting a local redis process. Not impossible of course, but I'm not sure the added setup is worth it...
Using `FakeRedis`, I've have yet to run into any disparity yet (but maybe thats anecdotal).
I'm gonna like this one open for now, and we re-address it when we have multiple backends.
