### ISSUE TITLE
Rediss

### ISSUE THREAD

**Issue by gustavoalmeida** [cameronmaske/celery-once#94]
Hello all

What about urls with rediss://? We are not allowing this protocol here?
https://github.com/cameronmaske/celery-once/blob/master/celery_once/backends/redis.py#L29

**Comment by cameronmaske** [comment]
Hi @gustavoalmeida 

Didn't know `rediss` was a thing! It isn't excluded for a particular reason. 
PR welcome if you'd like to extend it to include `rediss://`

**Comment by gustavoalmeida** [comment]
Hi @cameronmaske ,

Could you please prioritize this PR #98?

Thank you

**Comment by cameronmaske** [comment]
@gustavoalmeida released in version 2.1.2
Thanks for the contribution!
