### ISSUE TITLE
Bug: OSError Filename too long

### ISSUE THREAD

**Issue by mlaythe** [cameronmaske/celery-once#96]
I'm using the `File` backend and I'm passing a relatively large dictionary as a param to the celery task. Is it possible to use a hash or something else instead of the function params to generate the task filename?

**Comment by xuhcc** [comment]
Thanks for report, I've submitted a PR with a fix.

**Comment by cameronmaske** [comment]
@mlaythe this is fixed in version 3.0.0.
Thanks for the fix @xuhcc
